version: "3"
services:
    db:
      image: postgres:latest
      container_name: reddit-postgres
      restart: always
      ports:
          - "5433:5433"
      environment:
          POSTGRES_USER: "${DB_USER_ID}"
          POSTGRES_PASSWORD: "${DB_USER_PW}"
      volumes:
          - ./data22:/var/lib/postgresql/data
      command: -p 5433